// Métadonnées localisées (title + description) des routes EN et pays (/ch,
// /be, /lu, /qc). Données pures, sans import : consommées au build (HTML
// statique, via api/_routes.js) ET côté client, où usePageMeta les charge à la
// demande sur les seules pages localisées — le texte localisé du HTML
// pré-rendu n'est ainsi plus écrasé par le titre français au rendu JS.

// Méta anglaises (title + description) par route, pour le HTML statique /en/...
export const ROUTE_META_EN = {
  '/':                            { title: 'Free Financial Calculators — Savings, FIRE, Budget | Simfinly', description: 'Free online financial calculators: compound interest, FIRE & financial independence, 50/30/20 budget, net worth and more. Instant results, no sign-up.' },
  '/simulateurs/epargne':         { title: 'Compound Interest Calculator — Savings Growth | Simfinly',       description: 'Project how your savings grow over time with compound interest and regular contributions. See the final balance for any rate, duration and monthly deposit.' },
  '/simulateurs/fire':            { title: 'FIRE Calculator — Financial Independence, Retire Early | Simfinly', description: 'Calculate the net worth you need to live off your investments and the age you reach financial independence. Based on the 4% rule, with Lean/Coast/Fat FIRE milestones.' },
  '/simulateurs/budget':          { title: '50/30/20 Budget Calculator — Needs, Wants, Savings | Simfinly',  description: 'Split your monthly budget with the 50/30/20 rule: needs, wants and savings. See your balance and savings rate in real time, with tailored tips.' },
  '/simulateurs/patrimoine':      { title: 'Net Worth Calculator — Track Your Wealth | Simfinly',            description: 'Consolidate your financial, real-estate and retirement assets to see your net worth and how it breaks down by asset class.' },
  '/simulateurs/cout-en-heures':  { title: 'Cost in Hours of Work Calculator — True Price | Simfinly',       description: 'Turn any purchase into real hours of work. Based on your salary, discover what a product or subscription truly costs in life-time rather than money.' },
  '/simulateurs/vie-en-semaines': { title: 'Your Life in Weeks Calculator — Visualize Your Lifetime | Simfinly', description: 'Visualize your entire life as a grid, one square per week. See the weeks you have lived, the weeks left and the summers ahead. Inspired by Your Life in Weeks.' },
  '/simulateurs/assurance-vie':   { title: 'French Life Insurance Calculator — Capital & Tax | Simfinly', description: 'Project the growth of a French assurance-vie policy and estimate the tax on your gains at withdrawal: the 8-year advantage, allowance, flat tax and social levies.' },
  '/simulateurs/rendement-locatif': { title: 'Rental Yield Calculator — Buy-to-Let Profitability | Simfinly', description: 'Calculate the gross and net yield of a French rental investment: rent, costs, monthly cash flow and return on equity. Instant, free, no sign-up.' },
  '/simulateurs/emprunt-immobilier': { title: 'Mortgage Calculator — Monthly Payment & Borrowing Capacity | Simfinly', description: 'Work out your monthly payment, debt-to-income ratio and the total cost of a mortgage. Amortization schedule and total interest included.' },
  '/simulateurs/credit-conso':    { title: 'Personal Loan Calculator — Monthly Payment & Cost | Simfinly',   description: 'Calculate the monthly payment, total cost and total interest of a personal loan from the amount, APR and term. Includes optional insurance and an amortization schedule.' },
  '/simulateurs/comparateur':     { title: 'Asset Comparison Tool — ETFs, Stocks, Crypto | Simfinly',        description: 'Compare the historical performance of ETFs, stocks and cryptocurrencies over any period, from real data. Total return, CAGR, recurring contributions and base-100 index.' },
  '/outils/qr-code':              { title: 'Free Custom QR Code Generator — Color, Logo | Simfinly',         description: 'Create a custom QR code for free: pick the colors, enter any text or link and add your logo or an emoji in the center. High-resolution PNG, no sign-up.' },
  '/simulateurs/rente-capital':   { title: 'Annuity vs Programmed Withdrawal Simulator | Simfinly', description: 'Compare a life annuity and programmed withdrawals for your retirement savings. Monthly net income, break-even point and 20-year cumulative by tax bracket.' },
  '/simulateurs/inflation':       { title: 'Personal Inflation & Purchasing Power Simulator | Simfinly', description: 'Measure how inflation erodes your budget by spending category. Customize rates for food, housing, transport and more — project the impact over 10 to 30 years.' },
  '/mentions-legales':            { title: 'Legal notice — Simfinly',                                        description: 'Legal notice for simfinly.com: publisher, host, intellectual property and liability.' },
  '/politique-de-confidentialite':{ title: 'Privacy policy — Simfinly',                                       description: 'Privacy and cookie policy for simfinly.com: data collected, Google AdSense, GDPR.' },
  '/contact':                     { title: 'Contact — Simfinly',                                             description: 'Contact the simfinly.com team: questions about a calculator, error reports, partnership or press enquiries. Reply within 48 business hours.' },
  '/simulateurs/cnav':            { title: 'French State Pension Calculator (CNAV) 2026 — Estimate Your Retirement', description: 'Calculate your French state pension (régime général CNAV): quarters, average salary, departure age, pro-rata. Useful for expatriates and cross-border workers.' },
  '/simulateurs/retraite-luxembourg': { title: 'Luxembourg Pension Calculator (CNAP) 2026 — pension & replacement rate', description: 'Estimate your Luxembourg CNAP pension based on your career, salary and retirement age. Built for cross-border workers and expats employed in Luxembourg.' },
  '/comparatifs': { title: 'Financial Comparisons — PER vs Life Insurance, Buy vs Rent | Simfinly', description: 'Compare French financial products side by side: PER vs assurance-vie, buying vs renting, freelance vs employee. Data-driven comparisons to help you choose.' },
  '/lexique': { title: 'Financial Glossary — Clear Definitions | Simfinly', description: 'Glossary of personal finance terms: compound interest, FIRE, savings rate, debt-to-income ratio, rental yield, 4% rule… Simple definitions, linked to our free calculators.' },
  '/widgets':     { title: 'Free Embeddable Financial Calculators — Widgets | Simfinly', description: 'Embed free financial calculators on your website: compound interest, FIRE, mortgage, budget and French pension. Copy-paste the iframe code.' },
  '/simulateurs/donation': { title: 'French Gift Tax Calculator (Donation) 2026 | Simfinly', description: 'Estimate French gift tax (droits de donation) between parents and children: allowances, tax brackets and net amount received.' },
  '/simulateurs/pension-reversion': { title: 'French Survivor Pension Calculator 2026 — Private Sector & Civil Service | Simfinly', description: 'Estimate the French survivor pension (pension de réversion): 54% base + 60% Agirc-Arrco for private-sector employees, or 50% for civil servants (SRE/CNRACL), with means-testing where it applies.' },
};

// Méta suisses (title + description) pour le HTML statique /ch/...
export const ROUTE_META_CH = {
  '/':                                    { title: 'Simfinly — Simulateurs gratuits LPP, pilier 3a, fiscalité & finances (Suisse)',      description: 'Simulez votre 2e pilier LPP, votre pilier 3a, votre impôt cantonal et votre épargne. Simulateurs gratuits adaptés au droit suisse, sans inscription.' },
  '/simulateurs/lpp-deuxieme-pilier':     { title: 'Simulateur LPP 2e pilier Suisse 2025 — avoir de vieillesse & rente projetés',        description: 'Estimez votre avoir de vieillesse LPP et votre rente du 2e pilier selon votre salaire coordonné, vos années de cotisation et les taux d\'intérêt LPP 2025. Calcul instantané, sans inscription.' },
  '/simulateurs/impot-revenu-ch':         { title: 'Simulateur impôt sur le revenu Suisse 2025 — fédéral + cantonal',                    description: 'Calculez votre impôt fédéral direct et votre impôt cantonal selon votre canton, votre revenu imposable et votre situation familiale. Barèmes 2025 pour tous les cantons suisses.' },
  '/simulateurs/prevoyance-ch':           { title: 'Simulateur pilier 3a Suisse 2025 — capital projeté & déduction fiscale',              description: 'Projetez le capital de votre pilier 3a et estimez l\'économie d\'impôt annuelle. Calcul selon le plafond 2025 (CHF 7 258) et votre tranche cantonale.' },
  '/simulateurs/epargne':                 { title: 'Simulateur épargne & intérêts composés en CHF — projection long terme (Suisse)',      description: 'Projetez la croissance de votre épargne en francs suisses sur le long terme. Capital final selon le rendement, la durée et l\'effort mensuel en CHF.' },
  '/simulateurs/fire':                    { title: 'Simulateur FIRE en CHF — indépendance financière & retraite anticipée (Suisse)',      description: 'Calculez le patrimoine en CHF nécessaire pour vivre de vos investissements et l\'âge auquel vous atteignez l\'indépendance financière en Suisse. Règle des 4 %, paliers Lean/Coast/Fat FIRE.' },
  '/simulateurs/budget':                  { title: 'Simulateur budget 50/30/20 en CHF — finances personnelles Suisse',                   description: 'Répartissez votre budget mensuel en francs suisses selon la règle 50/30/20 : besoins, envies, épargne. Taux d\'épargne et conseils adaptés à votre situation.' },
  '/simulateurs/patrimoine':              { title: 'Simulateur patrimoine global en CHF — richesse nette & répartition (Suisse)',         description: 'Consolidez vos actifs financiers et immobiliers en francs suisses pour visualiser votre richesse nette et sa répartition par classe d\'actifs.' },
  '/simulateurs/emprunt-immobilier':      { title: 'Simulateur emprunt immobilier Suisse — mensualités & capacité en CHF',               description: 'Calculez la mensualité, la capacité d\'emprunt et le coût total de votre crédit immobilier en CHF. Tableau d\'amortissement annuel inclus.' },
  '/simulateurs/rendement-locatif':       { title: 'Simulateur rendement locatif en CHF — rentabilité brute & nette (Suisse)',           description: 'Évaluez la rentabilité brute et nette d\'un investissement locatif en Suisse, en CHF. Cash flow mensuel et retour sur fonds propres.' },
  '/simulateurs/assurance-vie':           { title: 'Simulateur épargne & assurance-vie en CHF — rendement & capital (Suisse)',           description: 'Projetez la croissance de votre épargne en francs suisses et estimez le capital disponible à l\'échéance.' },
  '/simulateurs/rente-capital':           { title: 'Simulateur rente viagère vs retrait programmé en CHF — retraite Suisse',             description: 'Comparez la rente viagère et les retraits programmés pour votre capital retraite en CHF. Revenu mensuel net, point mort et cumulatif 20 ans.' },
  '/simulateurs/inflation':               { title: 'Simulateur inflation & pouvoir d\'achat en CHF — Suisse 2025',                       description: 'Mesurez l\'impact de l\'inflation sur votre budget en francs suisses, par poste de dépense. Érosion du pouvoir d\'achat projetée sur 10 à 30 ans.' },
  '/simulateurs/comparateur':             { title: 'Comparateur d\'actifs ETF, actions, crypto en CHF — performance historique',         description: 'Comparez la performance historique d\'ETF, actions et cryptomonnaies sur la période de votre choix, en CHF. CAGR, versements programmés et indice base 100.' },
  '/simulateurs/credit-conso':            { title: 'Simulateur crédit à la consommation en CHF — mensualité & coût (Suisse)',            description: 'Calculez la mensualité et le coût total de votre crédit conso en francs suisses selon le montant, le TAEG et la durée.' },
  '/simulateurs/cout-en-heures':          { title: 'Simulateur prix en heures de vie en CHF — vrai coût d\'un achat (Suisse)',           description: 'Convertissez n\'importe quel achat en heures de travail réelles, en CHF. Le vrai coût d\'un bien ou d\'un abonnement exprimé en temps.' },
  '/simulateurs/vie-en-semaines':         { title: 'Simulateur ma vie en semaines — visualiser son temps (Suisse)',                      description: 'Visualisez votre vie entière sous forme de grille, une case par semaine. Semaines vécues, semaines restantes et étés encore à venir.' },
};

// Méta belges (title + description) pour le HTML statique /be/...
export const ROUTE_META_BE = {
  '/':                                    { title: 'Simfinly — Simulateurs gratuits pension, IPP, succession & finances (Belgique)',     description: 'Simulez votre pension légale ONSS, votre IPP, vos droits de succession et votre épargne. Simulateurs gratuits adaptés à la législation belge 2025, sans inscription.' },
  '/simulateurs/pension-legale':          { title: 'Simulateur pension légale Belgique ONSS 2025 — salarié & indépendant',              description: 'Estimez votre pension légale belge (ONSS) selon votre carrière, votre statut et votre âge de départ. Calcul selon les barèmes 2025 de la pension de retraite et de survie.' },
  '/simulateurs/impot-revenu':            { title: 'Simulateur IPP 2025 — impôt des personnes physiques Belgique',                      description: 'Calculez votre impôt des personnes physiques (IPP) belge selon votre revenu imposable, votre situation familiale et les barèmes 2025. Estimation nette après déductions.' },
  '/simulateurs/succession':              { title: 'Simulateur droits de succession Belgique 2025 — barème régional',                   description: 'Calculez les droits de succession belges selon la Région (Flandre, Wallonie, Bruxelles), le lien de parenté et l\'actif net. Barèmes 2025 officiels.' },
  '/simulateurs/epargne':                 { title: 'Simulateur épargne & intérêts composés en EUR — projection long terme (Belgique)',  description: 'Projetez la croissance de votre épargne en euros sur le long terme. Capital final selon le rendement, la durée et l\'effort mensuel en EUR.' },
  '/simulateurs/fire':                    { title: 'Simulateur FIRE — indépendance financière & retraite anticipée (Belgique)',         description: 'Calculez le patrimoine nécessaire pour vivre de vos investissements en Belgique et l\'âge auquel vous atteignez l\'indépendance financière. Règle des 4 %, paliers Lean/Coast/Fat FIRE.' },
  '/simulateurs/budget':                  { title: 'Simulateur budget 50/30/20 — finances personnelles Belgique',                      description: 'Répartissez votre budget mensuel selon la règle 50/30/20 : besoins, envies, épargne. Taux d\'épargne et conseils adaptés à la situation belge.' },
  '/simulateurs/patrimoine':              { title: 'Simulateur patrimoine global — richesse nette & répartition (Belgique)',            description: 'Consolidez vos actifs financiers et immobiliers pour visualiser votre richesse nette et sa répartition par classe d\'actifs, en contexte belge.' },
  '/simulateurs/emprunt-immobilier':      { title: 'Simulateur emprunt immobilier Belgique — mensualités & capacité',                  description: 'Calculez la mensualité, la capacité d\'emprunt et le coût total de votre crédit hypothécaire en Belgique. Tableau d\'amortissement annuel inclus.' },
  '/simulateurs/rendement-locatif':       { title: 'Simulateur rendement locatif Belgique — rentabilité brute & nette',                description: 'Évaluez la rentabilité brute et nette d\'un investissement locatif en Belgique. Cash flow mensuel et retour sur fonds propres.' },
  '/simulateurs/assurance-vie':           { title: 'Simulateur épargne-pension & assurance groupe — capital Belgique',                 description: 'Projetez la croissance de votre épargne-pension ou assurance groupe en Belgique et estimez le capital disponible à l\'échéance.' },
  '/simulateurs/rente-capital':           { title: 'Simulateur rente viagère vs retrait programmé — retraite Belgique',                description: 'Comparez la rente viagère et les retraits programmés pour votre capital retraite. Revenu mensuel net, point mort et cumulatif 20 ans.' },
  '/simulateurs/inflation':               { title: 'Simulateur inflation & pouvoir d\'achat — Belgique 2025',                          description: 'Mesurez l\'impact de l\'inflation sur votre budget en euros, par poste de dépense. Érosion du pouvoir d\'achat projetée sur 10 à 30 ans selon l\'indice belge.' },
  '/simulateurs/comparateur':             { title: 'Comparateur d\'actifs ETF, actions, crypto — Belgique',                            description: 'Comparez la performance historique d\'ETF, actions et cryptomonnaies sur la période de votre choix. CAGR, versements programmés et indice base 100.' },
  '/simulateurs/credit-conso':            { title: 'Simulateur crédit à la consommation — mensualité & coût Belgique',                 description: 'Calculez la mensualité et le coût total de votre crédit conso selon le montant, le TAEG et la durée. Adapté au marché belge.' },
  '/simulateurs/cout-en-heures':          { title: 'Simulateur prix en heures de vie — vrai coût d\'un achat (Belgique)',              description: 'Convertissez n\'importe quel achat en heures de travail réelles. Le vrai coût d\'un bien ou d\'un abonnement exprimé en temps plutôt qu\'en euros.' },
};

// Méta luxembourgeoises (title + description) pour le HTML statique /lu/...
export const ROUTE_META_LU = {
  '/':                                    { title: 'Simfinly — Simulateurs gratuits retraite CNAP, impôt, succession (Luxembourg)', description: 'Simulez votre pension CNAP, votre impôt sur le revenu et vos droits de succession au Luxembourg. Simulateurs gratuits pour frontaliers et résidents, sans inscription.' },
  '/simulateurs/retraite-luxembourg':     { title: 'Simulateur retraite Luxembourg (CNAP) 2026 — pension & taux de remplacement', description: 'Estimez votre pension CNAP luxembourgeoise selon votre carrière, salaire et âge de départ. Conçu pour les frontaliers et expatriés travaillant au Luxembourg.' },
  '/simulateurs/impot-revenu-lu':         { title: 'Simulateur impôt sur le revenu Luxembourg 2026 — classes 1, 1a, 2',            description: 'Calculez votre impôt luxembourgeois selon le barème progressif à 23 tranches, votre classe d\'impôt et la contribution au fonds pour l\'emploi. Estimation pour frontaliers et résidents.' },
  '/simulateurs/succession-lu':           { title: 'Simulateur droits de succession Luxembourg 2026 — ligne directe, conjoint',    description: 'Estimez les droits de succession luxembourgeois selon le lien de parenté : exonération en ligne directe et conjoint, barème progressif pour les autres héritiers.' },
  '/simulateurs/epargne':                 { title: 'Simulateur épargne & intérêts composés en EUR — projection long terme (Luxembourg)', description: 'Projetez la croissance de votre épargne en euros sur le long terme. Capital final selon le rendement, la durée et l\'effort mensuel en EUR.' },
  '/simulateurs/fire':                    { title: 'Simulateur FIRE — indépendance financière & retraite anticipée (Luxembourg)',  description: 'Calculez le patrimoine nécessaire pour vivre de vos investissements au Luxembourg et l\'âge auquel vous atteignez l\'indépendance financière. Règle des 4 %, paliers Lean/Coast/Fat FIRE.' },
  '/simulateurs/budget':                  { title: 'Simulateur budget 50/30/20 — finances personnelles Luxembourg',              description: 'Répartissez votre budget mensuel selon la règle 50/30/20 : besoins, envies, épargne. Taux d\'épargne et conseils adaptés à la situation luxembourgeoise.' },
  '/simulateurs/patrimoine':              { title: 'Simulateur patrimoine global — richesse nette & répartition (Luxembourg)',     description: 'Consolidez vos actifs financiers et immobiliers pour visualiser votre richesse nette et sa répartition par classe d\'actifs, en contexte luxembourgeois.' },
  '/simulateurs/emprunt-immobilier':      { title: 'Simulateur emprunt immobilier Luxembourg — mensualités & capacité',           description: 'Calculez la mensualité, la capacité d\'emprunt et le coût total de votre crédit hypothécaire au Luxembourg. Tableau d\'amortissement annuel inclus.' },
  '/simulateurs/rendement-locatif':       { title: 'Simulateur rendement locatif Luxembourg — rentabilité brute & nette',         description: 'Évaluez la rentabilité brute et nette d\'un investissement locatif au Luxembourg. Cash flow mensuel et retour sur fonds propres.' },
  '/simulateurs/assurance-vie':           { title: 'Simulateur épargne & assurance-vie en EUR — capital Luxembourg',              description: 'Projetez la croissance de votre épargne en euros et estimez le capital disponible à l\'échéance, au Luxembourg.' },
  '/simulateurs/comparateur':             { title: 'Comparateur d\'actifs ETF, actions, crypto — Luxembourg',                     description: 'Comparez la performance historique d\'ETF, actions et cryptomonnaies sur la période de votre choix. CAGR, versements programmés et indice base 100.' },
  '/simulateurs/credit-conso':            { title: 'Simulateur crédit à la consommation — mensualité & coût Luxembourg',          description: 'Calculez la mensualité et le coût total de votre crédit conso selon le montant, le TAEG et la durée. Adapté au marché luxembourgeois.' },
  '/simulateurs/cout-en-heures':          { title: 'Simulateur prix en heures de vie — vrai coût d\'un achat (Luxembourg)',       description: 'Convertissez n\'importe quel achat en heures de travail réelles. Le vrai coût d\'un bien ou d\'un abonnement exprimé en temps plutôt qu\'en euros.' },
};

// Méta québécoises (title + description) pour le HTML statique /qc/...
export const ROUTE_META_QC = {
  '/':                                    { title: 'Simfinly — Simulateurs gratuits retraite RRQ, épargne, budget (Québec)',      description: 'Simulez votre rente RRQ, votre épargne et votre budget en dollars canadiens. Simulateurs gratuits adaptés au Québec, sans inscription.' },
  '/simulateurs/retraite-quebec':         { title: 'Simulateur retraite RRQ 2026 — rente du Régime de rentes du Québec',          description: 'Estimez votre rente RRQ selon votre revenu de carrière et l\'âge de départ choisi (60 à 70 ans). Basé sur les paramètres 2026 de Retraite Québec.' },
  '/simulateurs/impot-revenu-qc':         { title: 'Simulateur impôt sur le revenu Québec 2026 — provincial + fédéral',          description: 'Calculez votre impôt québécois combiné (provincial et fédéral, avec l\'abattement de 16,5 %) selon le barème progressif 2026.' },
  '/simulateurs/epargne':                 { title: 'Simulateur épargne & intérêts composés en CAD — projection long terme (Québec)', description: 'Projetez la croissance de votre épargne en dollars canadiens sur le long terme. Capital final selon le rendement, la durée et l\'effort mensuel.' },
  '/simulateurs/fire':                    { title: 'Simulateur FIRE — indépendance financière & retraite anticipée (Québec)',     description: 'Calculez le patrimoine nécessaire pour vivre de vos investissements au Québec et l\'âge auquel vous atteignez l\'indépendance financière. Règle des 4 %, paliers Lean/Coast/Fat FIRE.' },
  '/simulateurs/budget':                  { title: 'Simulateur budget 50/30/20 — finances personnelles Québec',                  description: 'Répartissez votre budget mensuel selon la règle 50/30/20 : besoins, envies, épargne. Taux d\'épargne et conseils adaptés à la situation québécoise.' },
  '/simulateurs/patrimoine':              { title: 'Simulateur patrimoine global — richesse nette & répartition (Québec)',        description: 'Consolidez vos actifs financiers et immobiliers pour visualiser votre richesse nette et sa répartition par classe d\'actifs, en contexte québécois.' },
  '/simulateurs/emprunt-immobilier':      { title: 'Simulateur emprunt immobilier Québec — mensualités & capacité',              description: 'Calculez la mensualité, la capacité d\'emprunt et le coût total de votre prêt hypothécaire au Québec. Tableau d\'amortissement annuel inclus.' },
  '/simulateurs/rendement-locatif':       { title: 'Simulateur rendement locatif Québec — rentabilité brute & nette',            description: 'Évaluez la rentabilité brute et nette d\'un investissement locatif au Québec. Cash-flow mensuel et retour sur fonds propres.' },
  '/simulateurs/assurance-vie':           { title: 'Simulateur épargne & assurance-vie en CAD — capital Québec',                 description: 'Projetez la croissance de votre épargne en dollars canadiens et estimez le capital disponible à l\'échéance, au Québec.' },
  '/simulateurs/comparateur':             { title: 'Comparateur d\'actifs ETF, actions, crypto — Québec',                        description: 'Comparez la performance historique d\'ETF, actions et cryptomonnaies sur la période de votre choix. CAGR, versements programmés et indice base 100.' },
  '/simulateurs/credit-conso':            { title: 'Simulateur crédit à la consommation — mensualité & coût Québec',             description: 'Calculez la mensualité et le coût total de votre crédit conso selon le montant, le taux et la durée. Adapté au marché québécois.' },
  '/simulateurs/cout-en-heures':          { title: 'Simulateur prix en heures de vie — vrai coût d\'un achat (Québec)',          description: 'Convertissez n\'importe quel achat en heures de travail réelles. Le vrai coût d\'un bien ou d\'un abonnement exprimé en temps plutôt qu\'en dollars.' },
};

const BY_COUNTRY = { ch: ROUTE_META_CH, be: ROUTE_META_BE, lu: ROUTE_META_LU, qc: ROUTE_META_QC };

// Méta localisée d'une route canonique pour une locale / un pays, ou null.
export function localizedRouteMeta(route, locale = 'fr', country = 'fr') {
  if (locale === 'en') return ROUTE_META_EN[route] || null;
  return BY_COUNTRY[country]?.[route] || null;
}
